export const ResultSampleData = {
  studentInfo: {
    name: 'Qasim',
    fatherName: 'Amjad',
    class: '9th',
    rollNo: '615872',
  },
  tests: [
    {
      testName: 'Test 1',
      subjects: {
        Maths: 30,
        Urdu: 47,
        English: 54,
        AlQuran: 30,
        Islamic: 28,
        BioCom: 29,
        Physics: 28,
        Chemistry: 28,
      },
      total: 274,
      percentage: 94.48,
      grade: 'A+',
    },
    {
      testName: 'Test 2',
      subjects: {
        Maths: 22,
        Urdu: 47,
        English: 58,
        AlQuran: 30,
        Islamic: 27,
        BioCom: 27,
        Physics: 27,
        Chemistry: 22,
      },
      total: 263,
      percentage: 90.69,
      grade: 'A+',
    },
    {
      testName: 'Test 3',
      subjects: {
        Maths: 23,
        Urdu: 42,
        English: 54,
        AlQuran: 30,
        Islamic: 29,
        BioCom: 29,
        Physics: 26,
        Chemistry: 25,
      },
      total: 259,
      percentage: 89.31,
      grade: 'A+',
    },
    {
      testName: 'Test 4',
      subjects: {
        Maths: 29,
        Urdu: 47,
        English: 58,
        AlQuran: 30,
        Islamic: 24,
        BioCom: 27,
        Physics: 28,
        Chemistry: 30,
      },
      total: 273,
      percentage: 94.14,
      grade: 'A+',
    },
    {
      testName: 'Test 5',
      subjects: {
        Maths: 28,
        Urdu: 41,
        English: 57,
        AlQuran: 30,
        Islamic: 29,
        BioCom: 24,
        Physics: 27,
        Chemistry: 28,
      },
      total: 264,
      percentage: 91.03,
      grade: 'A+',
    },
    {
      testName: 'Test 6',
      subjects: {
        Maths: 26,
        Urdu: 36,
        English: 56,
        AlQuran: 29,
        Islamic: 26,
        BioCom: 26,
        Physics: 26,
        Chemistry: 30,
      },
      total: 253,
      percentage: 87.24,
      grade: 'A+',
    },
    {
      testName: 'Test 7',
      subjects: {
        Maths: 27,
        Urdu: 44,
        English: 54,
        AlQuran: 29,
        Islamic: 26,
        BioCom: 28,
        Physics: 28,
        Chemistry: 29,
      },
      total: 267,
      percentage: 92.07,
      grade: 'A+',
    },
    {
      testName: 'Test 8',
      subjects: {
        Maths: 26,
        Urdu: 40,
        English: 58,
        AlQuran: 30,
        Islamic: 26,
        BioCom: 22,
        Physics: 29,
        Chemistry: 0,
      },
      total: 230,
      percentage: 87.39,
      grade: 'A+',
    },
  ],
  behaviour: 'Excellent',
  uniformCleanliness: 'Excellent',
  overallResult: {
    obtainedMarks: 4108,
    totalMarks: 4520,
    percentage: 90.88,
    grade: 'A+',
    status: 'PASS',
    remarks:
      "Excellent Performance Overall. Don't Be Lazy. More Hardwork Makes You More Successful. In sha ALLAH",
  },
};
